---
- name: Install the nginx service
  template: src=nginx.service.j2 dest=/etc/systemd/system/nginx-app.service mode=0644 owner=root group=root
  notify:
    - reload systemd

- name: Enable nginx-app service
  service: name=nginx-app state=started enabled=yes
