---
- include: fedora.yml
  when: ansible_distribution == 'Fedora'

- name: Enable docker-gc for cleanup
  cron:
    name: "docker-gc cleanup"
    state: present
    user: root
    hour: "*/1"
    job: "docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /etc:/etc spotify/docker-gc || :"

- name: Enable cleanup of unused volumes
  cron:
    name: "clean docker volumes"
    state: present
    user: root
    hour: "*/1"
    job: "docker volume rm $(docker volume ls -qf dangling=true) || :"
